### ISSUE TITLE
Lord and Saviour

### ISSUE THREAD

**Issue by ghost** [Lilwiggy/PennyJS#11]
Hello, do you have a moment time to speak about our lord and saviour promisify and async/await?

Such as
https://github.com/Lilwiggy/Penny/blob/cfd381ed561824dc15925b7c382d9a1cfe5a738c/commands/hug.js#L22

**Comment by Lilwiggy** [comment]
Could you elaborate please

**Comment by ghost** [comment]
Promisify `connection.query` (and all other callback functions) and use async/await.

**Comment by Lilwiggy** [comment]
Yeah I guess I could. I'm not doing anymore heavy dev work on it though since I'm about to swap over to C#

**Comment by ghost** [comment]
This is inacceptable.
